### ISSUE TITLE
Note not being created when preset created - am using it right?

### ISSUE THREAD

**Issue by muteboy** [aviskase/obsidian-link-indexer#14]
Hi,
I've created a preset, but I can't see any way to run or activate it. The note is not created automatically. Am I missing something obvious?

v0.9.20 Windows 10

**Comment by aviskase** [comment]
Hi, there is no autocreation,  you need to run a command via command palette.

**Comment by aviskase** [comment]
@muteboy hi, was my answer enough and I can close this issue?

**Comment by muteboy** [comment]
Hi,
Thanks for your answer, yes, you can close.
