### ISSUE TITLE
Command not producing index file

### ISSUE THREAD

**Issue by ghost** [aviskase/obsidian-link-indexer#15]
Hi, the command is not producing any file under the specified folder. I wonder if I'm writing the folder name in the wrong format. I tried:
FolderName
\FolderName
.\FolderName

None works.
macOS 10.12, Obsidian 0.11

**Comment by aviskase** [comment]
@Gattomarino are you referring to "All used links" path option? It expects the whole path, not just a folder name. For example ` .\FolderName\test.md`

**Comment by ghost** [comment]
oh I see, yes it makes sense. And it works :-)
Thanks!

Il giorno mar 23 feb 2021 alle ore 01:13 Yuliya Bagriy <
notifications@github.com> ha scritto:
