### ISSUE TITLE
bug: Plugin options vanished after restarting obsidian 

### ISSUE THREAD

**Issue by thorstenmerl** [aviskase/obsidian-link-indexer#16]
Plugin options are available after activating the plugin but are gone after restarting obsidian.

**Comment by aviskase** [comment]
@herixa hi
1) what's your system?

2) Can you see any errors in devtools? (open devtools by using key combination `Ctrl+Shift+I`  and open Console tab)

**Comment by thorstenmerl** [comment]
Hi, I'm sorry, I made a mistake. The plugin options are there as they should be.
I just hadn't seen that they change the position on restart. At first they are at the bottom and than somehow somewhere in the middle (I don't get why they are sorted like that):
![image](https://user-images.githubusercontent.com/71291080/113353603-39170f00-933e-11eb-9d7b-8bdb2b028844.png)

sorry for any inconvenience

**Comment by aviskase** [comment]
And me sorry for late response.
No worries, I guess, the order isn't stable.
