### ISSUE TITLE
Detailed instructions on how to use it?

### ISSUE THREAD

**Issue by luiandresgonzalez** [aviskase/obsidian-link-indexer#17]
Hi, I think I am missing something about this plugin on how to use it. I've installed and activated it, but no new sidebar buttons or command palette items have appeared. Using 0.12.12

**Comment by aviskase** [comment]
Hi, I'm no longer using it myself, but I've added this to the Readme:

>  To configure the plugin, go to plugin settings and add a preset with desired configuration. After that you'll see a new command added to the palette with the name `Link indexer: Used links - {name of the preset}`.

Is it clear enough?
